// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ChakraProvider, Box } from "@chakra-ui/react";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Company Profile",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <Box bg="black" minH="100vh" color="white">
            <Navbar />
            {children}
            <Footer/>
          </Box>
        </ChakraProvider>
      </body>
    </html>
  );
}
